# https://github.com/wmnnd/nginx-certbot
# https://scribe.rip/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71
services:
  nginx:
    container_name: nginx
    image: nginx:1.25.1-alpine
    # image: nginx:dev
    # build:
    #   context: nginx.dev
    #   dockerfile: nginx.dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx.dev/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.dev/conf.d:/etc/nginx/conf.d

      - ./nginx.dev/certbot/conf:/etc/letsencrypt
      - ./nginx.dev/certbot/www:/var/www/certbot

      - ./logs/nginx:/var/log/nginx/
    # command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx'"

  certbot:
    image: certbot/dns-route53
    restart: unless-stopped
    volumes:
      - ./nginx.dev/certbot/conf:/etc/letsencrypt
      - ./nginx.dev/certbot/www:/var/www/certbot

      - ./logs/certbot:/var/log/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    env_file:
      - .env.certbot

  backend:
    container_name: backend
    image: backend:dev
    build:
      context: .
    restart: on-failure
    entrypoint: ["./node_modules/.bin/vite-node", "src/server.ts"]
    volumes:
      - ./backend/src:/app/backend/src

      - ./logs/backend:/app/backend/logs
    env_file: .env.https
    environment:
      - MODE=https
      - TZ=Asia/Seoul
