name: 새 제안
description: 새로운 제안을 작성합니다.

labels: [proposal]

body:
  - type: textarea
    id: description
    attributes:
      label: 제안 설명
      description: 어떤 제안을 하고 싶은지 설명해주세요.
      placeholder: |
        예시:
        - [ ] '...' 기능을 구현합니다.
        - [ ] '...' 기능을 구현합니다.
    validations:
      required: true
