site_name: 집현전 개발 가이드
theme:
  name: material
  language: ko

extra:
  static_dirs:
    - docs/image

markdown_extensions:
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
