name: Deploy to OCI

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: setup pnpm
        run: |
              corepack enable
              corepack prepare pnpm@latest-8 --activate
              pnpm config set store-dir .pnpm-store

      - name: install dependencies
        working-directory: backend
        run: pnpm install

      - name: Deploy
        uses: appleboy/ssh-action@master
        env:
          INPUT_HOST: ${{ secrets.OCL_IP }}
          INPUT_USERNAME: ${{ secrets.OCL_USER }}
          INPUT_KEY: ${{ secrets.OCL_KEY }}
          INPUT_PORT: ${{ secrets.OCL_PORT }}
        with:
          port: $INPUT_PORT
          host: $INPUT_HOST
          username: $INPUT_USERNAME
          key: $INPUT_KEY
          script: |
            cd /home/opc/backend
            git pull
            cd backend
            sudo docker compose down
            sudo docker compose up -d --build
