name: Deploy to OCI

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: oracle deployment

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: setup pnpm
        run: |
              corepack enable
              corepack prepare pnpm@latest-8 --activate
              pnpm config set store-dir .pnpm-store

      - name: install dependencies
        working-directory: backend
        run: pnpm install

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          port: ${{ secrets.OCL_PORT }}
          username: ${{ secrets.OCL_USER }}
          key: ${{ secrets.OCL_KEY }}
          host: ${{ secrets.OCL_IP }}
          script: |
            cd /home/opc/backend
            git pull
            
            sudo docker compose \
            -e MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} \
            -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e BACKUP_USER=${{ secrets.BACKUP_USER}} \
            -e BACKUP_PASSWORD=${{ secrets.BACKUP_PASSWORD }} \
            -e ADMIN_SLACK_ID=${{ secrets.ADMIN_SLACK_ID }} \
            -e DB_SCHEMA=${{ secrets.DB_SCHEMA }} \
            -e MODE=${{ secrets.MODE }} \
            -e NODE_ENV=${{ secrets.NODE_ENV }} \
            -e CLIENT_ID=${{ secrets.CLIENT_ID }} \
            -e CLIENT_SECRET=${{ secrets.CLIENT_SECRET }} \
            -e REDIRECT_URL=${{ secrets.REDIRECT_URL }} \
            -e CLIENT_URL=${{ secrets.CLIENT_URL }} \
            -e BOT_USER_OAUTH_ACCESS_TOKEN=${{ secrets.BOT_USER_OAUTH_ACCESS_TOKEN }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e NAVER_BOOK_SEARCH_CLIENT_ID=${{ secrets.NAVER_BOOK_SEARCH_CLIENT_ID }} \
            -e NATION_LIBRARY_KEY=${{ secrets.NATION_LIBRARY_KEY }} \
            -e NAVER_BOOK_SEARCH_SECRET=${{ secrets.NAVER_BOOK_SEARCH_SECRET }} \
            -d --build
            sudo docker compose down
