name: Deploy to OCI

on:
  workflow_dispatch:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: setup pnpm
        run: |
              corepack enable
              corepack prepare pnpm@latest-8 --activate
              pnpm config set store-dir .pnpm-store

      - name: Install dependencies
        working-directory: backend
        run: pnpm install

      - name: Build
        working-directory: backend
        run: pnpm run build

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCL_IP }}
          username: ${{ secrets.OCL_USER }}
          key: ${{ secrets.OCL_KEY }}
          port: ${{ secrets.OCL_PORT }}
          script: |
            cd /home/opc/backend
            git pull
            cd backend
            sudo docker compose down
            sudo docker compose up -d --build

          